[package]
name = "soroban-builtin-sdk-macros"
description = "Soroban builtin SDK macros."
homepage = "https://github.com/stellar/rs-soroban-env"
repository = "https://github.com/stellar/rs-soroban-env"
authors = ["Stellar Development Foundation <info@stellar.org>"]
license = "Apache-2.0"
version.workspace = true
edition = "2021"
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = {version="=2.0.43",features=["full"]}
quote = "=1.0.33"
proc-macro2 = "=1.0.86"
itertools = "=0.13.0"

[package.metadata.docs.rs]
all-features = true
