name: 'check for changes that should accompany env.json change'

on:
  pull_request:
    paths:
      - 'soroban-env-common/env.json'

jobs:
  check:
    if: "!contains( github.event.pull_request.labels.*.name, 'skip-env-interface-version-bump')"
    runs-on: 'ubuntu-20.04'
    steps:
    - name: "check soroban-env-common/src/meta.rs was modified"
      uses: brettcannon/check-for-changed-files@871d7b8b5917a4f6f06662e2262e8ffc51dff6d1
      with:
        file-pattern: "soroban-env-common/src/meta.rs"
    - name: "check 'pre_release_version:' changed in the diff"
      uses: graydon/gh-pr-content-checker@a85f72c50a84400bb3e0837555b5a50c985370e7
      with:
        github-token: ${{github.token}}
        diffContainsRegex: " pre_release_version: [0-9]+,"
    - name: "check soroban-test-wasms/wasm-workspace/opt/*.wasm were modified"
      uses: brettcannon/check-for-changed-files@871d7b8b5917a4f6f06662e2262e8ffc51dff6d1
      with:
        file-pattern: "soroban-test-wasms/wasm-workspace/opt/curr/*.wasm"
